const express = require('express')
const route = express.Router()
const adminController = require('../app/controllers/adminController')
const multer  = require('multer')
const upload = multer({ dest: 'uploads/' })

route.get('/', adminController.showProfile)

route.get('/admin-student',adminController.showManageStudent)
route.post('/admin-student/:nienkhoa',adminController.processManageStudentSelectClass)
route.post('/admin-student',adminController.processManageStudent)
route.get('/add-student/:nienkhoa',adminController.showAddNewStudent)
route.post('/add-student/:nienkhoa',adminController.storeNewStudent)
route.get('/select-nk',adminController.showSelectNk)
route.post('/select-nk',adminController.processSelectNk)
route.get('/update-student/:idhs',adminController.showUpdateStudent)
route.post('/update-student/:idhs',adminController.proccessUpdateStudent)
route.delete('/delete-student/:idhs',adminController.deleteStudent)

route.get('/admin-classroom',adminController.showManageClassroom)
route.post('/admin-classroom',adminController.processManageClassroom)
route.get('/selectNk-class',adminController.selectNienKhoaForClass)
route.post('/selectNk-class',adminController.proccessNienKhoaForClass)
route.get('/add-classroom/:nienkhoa',adminController.showAddNewClassroom)
route.post('/add-classroom/:nienkhoa',adminController.storeNewClassroom)
route.get('/update-classroom/:idlop',adminController.showUpdateClassroom)
route.post('/update-classroom/:idlop',adminController.proccessUpdateClassroom)
route.delete('/delete-classroom/:idlop',adminController.deleteClassroom)
route.get('/add-nienkhoa',adminController.showAddNewNienKhoa)
route.post('/add-nienkhoa',adminController.storeNewNienKhoa)

route.get('/admin-teacher',adminController.showManageTeacher)   
route.get('/add-teacher',adminController.showAddNewTeacher)
route.post('/add-teacher',adminController.storeNewTeacher)
route.get('/update-teacher/:idgv',adminController.showUpdateTeacher)
route.post('/update-teacher/:idgv',adminController.proccessUpdateTeacher)
route.delete('/delete-teacher/:idgv',adminController.deleteTeacher)

route.get('/admin-score',adminController.showManageScore)
route.post('/admin-score/:nienkhoa',adminController.proccessManageScoreNK)
route.post('/admin-score',adminController.proccessManageScore)
route.delete('/delete-score',adminController.deleteScore)
route.get('/add-list-score-ks',adminController.ShowAddScoreKS)
route.post('/add-list-score-ks', upload.single('danhSachDiemKS'), adminController.ProccessAddScoreKS)
route.get('/thoi-khoa-bieu-gv',adminController.showTKBGV)
route.post('/thoi-khoa-bieu-gv/:idGV',adminController.proccessTKBGV)
route.get('/update-tkb-gv/:idtkb',adminController.showUpdateTKBGV)
route.post('/update-tkb-gv/:idtkb',adminController.proccessUpdateTKBGV)
route.get('/add-tkb-gv/:giaovien',adminController.showAddTKBGV)
route.post('/add-tkb-gv/:giaovien',adminController.proccessAddTKBGV)
route.delete('/delete-tkb-gv/:idtkb',adminController.deleteTKBGV)

route.get('/tkb-student',adminController.showTKBHocSinh)
route.post('/tkb-student/:idlop',adminController.ProccessTKBHocSinh)
route.get('/add-tkb-student/:idlop',adminController.showAddTKBHocSinh)
route.post('/add-tkb-student/:idlop',adminController.proccessAddTKBHocSinh)
route.get('/update-tkb-student/:idtkb',adminController.showUpdateTKBHocSinh)
route.post('/update-tkb-student/:idtkb',adminController.proccessUpdateTKBHocSinh)
route.delete('/delete-tkb-student/:idtkb',adminController.deleteTKBHocSinh)

route.get('/thongbao',adminController.showThongBao)
route.delete('/delete-thongbao/:idtb',adminController.DeleteThongBao)
route.post('/add-thongbao',adminController.addThongBao)

route.get('/admin-setting',adminController.showSetting)
route.post('/admin-setting',adminController.processSetting)



module.exports = route